### DISCUSSION TITLE
New to Github Actions

### DISCUSSION THREAD

**Discussion by kuyazee** [kuhnroyal/flutter-fvm-config-action#13] [Q&A]
I'm new using Github actions and use your package. How do I use the `fvm` commands within GH actions?

![Screen Shot 2022-11-28 at 9 19 47 PM](https://user-images.githubusercontent.com/17846698/204287675-cdc0677e-bd92-49ab-9580-1cf44a52d17c.png)

Here's an example of my yaml

```yaml
jobs:
  fvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kuhnroyal/flutter-fvm-config-action@v1
        with:
          path: ".fvm/fvm_config.json"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

  build:
    runs-on: ubuntu-latest
    needs: fvm
    steps:
      - name: 📦 Install Dependencies
        run: |
          fvm flutter pub global activate very_good_cli
          very_good --analytics false
          very_good packages get --recursive

      - name: 🕵️ Analyze
        run: fvm flutter analyze lib test
```
