### ISSUE TITLE
Allow using specific flavor via parameter

### ISSUE THREAD

**Issue by DevNico** [kuhnroyal/flutter-fvm-config-action#10]
Allow specifyng the flavor to pull via a parameter `flavor`.

fvm_config.json
```json
{
  "flutterSdkVersion": "stable",
  "flavors": {
    "development": "stable",
    "staging": "3.3.7",
    "production": "2.10.5"
  }
}
```

workflow suggestion:
```yaml
- uses: kuhnroyal/flutter-fvm-config-action@v1
  with:
    flavor: staging
```
